### PR TITLE
Command: what is my name? whats my name? what's my name?

### PR DESCRIPTION
**Pull request by sebastiandero**
Hey, finished a `whats my name` command that supports quite generous variations!

### CODE REVIEW

**Comment by sebastiandero** [comment]
@ceci-woodward Hey, have a look at the code, tell me if it needs improvement

**Comment by sebastiandero** [comment]
Added a `whats my id` command aswell

**Comment by nick-woodward** [comment]
@sebastiandero currently the only pending changes are unit tests.

After that I'll merge this PR.

**Review by cecilia-sanare — CHANGES_REQUESTED** [review]
@sebastiandero currently the only pending changes are unit tests.

After that I'll merge this PR.

**Comment by nick-woodward** [comment]
@sebastiandero Sorry it took so long. 

I actually reviewed this 19 days ago, however I didn't realize GitHub 
makes you submit all the changes and then submit the entire 
review separately.

**Comment by sebastiandero** [comment]
@ceci-woodward Hey, sure, i can do some tests, never unit tested hubot before lets see how it goes

**Comment by sebastiandero** [comment]
@ceci-woodward do i understand correctly? test user alice has an id "alice" right?

**Comment by sebastiandero** [comment]
@ceci-woodward could you take a look if the testing is thorough enough?

**Review by cecilia-sanare — APPROVED** [review]
LGTM!

Thanks @sebastiandero!

**Comment by sebastiandero** [comment]
No problem!

**Comment by nick-woodward** [comment]
@sebastiandero Your changes should be present in hubot-auth@2.1.0!

**Comment by sebastiandero** [comment]
@ceci-woodward my pleasure!

**Pull request merged**
