### PR TITLE
Allow referring to self in the first-person for add/remove role commands

### PR DESCRIPTION
**Pull request by therealklanni**
Quite simply, allow "I" to refer to the user just like we do in the "what roles" command.

### CODE REVIEW

**Comment by patcon** [comment]
+1 looks good! Any chance you could copy-paste a test case to cover this?

**Comment by therealklanni** [comment]
Sure, np

**Comment by patcon** [comment]
Hm. Not sure what happened, but went from working after your first commit, to broken after you added the tests, so something happened:

* https://travis-ci.org/hubot-scripts/hubot-auth/jobs/49362001
* https://travis-ci.org/hubot-scripts/hubot-auth/jobs/49392453

Clearly, something is up with the way the tests are hooked up on travis, as it didn't fail out :/

It might have to do with your regex in line 90 where you added a new matching group when I don't think you needed to? Just looked briefly though

**Comment by therealklanni** [comment]
Are you certain? The tests passed locally even. I will take another look.

**Comment by therealklanni** [comment]
screen shot 2015-02-03 at 11 20 42 pm

Not sure what to say.

**Comment by patcon** [comment]
Yeah, odd. I had the same error locally, and started to investigate, but it was really weird. Like something was sticking around between tests somehow :/

Gimme a day or two to dig in, and if not, I'll just merge I suppose

**Comment by patcon** [comment]
Actually, it looks like it's just junk output, but it's not actually failing. I'll just merge :)

**Comment by patcon** [comment]
Tagged and releases in v1.2.0

**Comment by therealklanni** [comment]
Is there something else I should check?

**Comment by therealklanni** [comment]
Weird. Thanks!

**Pull request merged**
