### PR TITLE
Updated tests to use hubot-test-helper for test clarity

### PR DESCRIPTION
**Pull request by cecilia-sanare**
Also updated various packages to their latest version

This shaved off a few lines of code, however the big improvement in my mind is getting rid of the ambiguous message skipping you had to do with the adapters reply event.

### CODE REVIEW

**Comment by patcon** [comment]
cool! thoughts on resolving those failures?

**Comment by nick-woodward** [comment]
Seems to be related to Node 0.10 not supporting promises.

I'm going to change the Node versions to latest and stable that way we cover the versions people are likely to install.

**Comment by nick-woodward** [comment]
Resolved the issue with the old node versions being used with Travis.
Also squashed all of my commits into a single commit.

**Comment by patcon** [comment]
Thanks so much Cecilia, but the rebase actually makes this more difficult to actually review...! In the future, please either 1) not squash changes that include unnecessary style changes beyond the PR scope, or 2) not include style changes in with functional changes

I'll on the go right now, but will review later :) If you still have the reflog, and it's simple to revert and push, that would probably resolve the above concern. thanks!

**Comment by nick-woodward** [comment]
Sorry about that, reverted the squash.

**Comment by patcon** [comment]
Ugh. I'm an idiot. Sorry man. I didn't look closely enough and so didn't realize you'd totally rewritten. (which is awesome)

Thanks for reverting even though it wasn't sensible :)

**Pull request merged**
