### PR TITLE
Add a more general environment variable for adding a static set of roles

### LINKED ISSUE #31: As an Ops, I want to be able to configure hubot-auth roles in order to be idempotent
I don't see any mechanism to pre-configure some roles automatically (with an environment variable for instance).
I can install hubot-auth, setup some roles persisted in Redis Brain using hubot commands.

But, if my redis or hubot crash, I have to setup roles again.

What do you think ?

Best Regards

### PR DESCRIPTION
**Pull request by nick-woodward**
* Added the env variable to the README
* Deprecated HUBOT_AUTH_ADMIN

Closes #31

### CODE REVIEW

**Comment by patcon** [comment]
Nice! Any way we could easily make this backward compat so that it's not going to break hubot-auth for everyone using the current method? If we don't feel like being empathetic to those people, we could just do a major version bump next release, I suppose :)

**Comment by nick-woodward** [comment]
It still supports using HUBOT_AUTH_ADMIN, it just will output a warning letting developers know its deprecated.

**Comment by nick-woodward** [comment]
ping @patcon

**Comment by patcon** [comment]
Released in v1.3.0! Thanks! :fireworks:

**Comment by rambo45** [comment]
I have set the environment variable properly bu it fails with this error:
ERROR Unable to load /opt/bot/node_modules/hubot-auth/src/auth: TypeError: Cannot read property '0' of null
  at module.exports (/opt/bot/node_modules/hubot-auth/src/auth.coffee:48:36, <js>:35:70)
  at Robot.loadFile (/opt/bot/node_modules/hubot/src/robot.coffee:358:11, <js>:226:13)
  at /opt/bot/node_modules/hubot-auth/index.coffee:12:11, <js>:26:33
  at FSReqWrap.cb [as oncomplete] (fs.js:240:19)

**Comment by patcon** [comment]
Ah, shoot, sorry that it's giving you trouble @rambo45. I think you'll always have better luck getting a response from someone if you open a new issue? Maintainers usually like issues to be about one thing at a time :)

**Comment by benzvan** [comment]
I think I ran into similar problems trying to implement a similar feature. I tried to append role info to the existing hubot users, but I think it got overwritten when hubot connected to slack. I ended up creating my own auth plugin that uses hubot-auth but stores roles in a separate dictionary in the brain.

**Pull request merged**
